name: Publish Hugo CodifiedSecurity landing page

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: false
      - name: Hugo to GH Pages
        uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PAGES_TOKEN }}
          cname: slack.bridgecrew.io
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'CNAME'
          branch: gh-pages
